from . import (test_advection_1D,
               test_inlet_outlet,
               test_membrane_staggered,
               test_obstacles_collocated,
               test_obstacles_staggered,
               test_obstacles_thinner_staggered,
               test_p_tot_staggered,
               test_stratification_staggered,
               test_thermal_plumes_collocated,
               test_thermal_plumes_staggered,
               test_thermally_driven_cavity_collocated,
               test_thermally_driven_cavity_staggered)